Example how to generate the PDF directly in CI
Missing:
- artifact management where should the generated PDF go?
- probably fonts related stuff installation.

And there is an error that should be debugged:
```txt
UnboundLocalError: local variable 'i_header' referenced before assignment
```